fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      # Run the tests
      - id: pytest
        name: pytest
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      # Run type checks
      - id: mypy
        name: mypy
        stages: [commit]
        types: [python]
        entry: mypy dante
        language: system
        pass_filenames: false
